#!/bin/bash

# Beware! This script will be in /rom/etc/uci-defaults/ as part of the image.
# Uncomment lines to apply:
# log potential errors

exec >/tmp/setup.log 2>&1

[ "$(uci -q get system.@system[0].zonename)" = 'Asia/Shanghai' ] && exit 0

(echo "$root_password"; sleep 1; echo "$root_password") | passwd > /dev/null

uci set system.@system[0].zonename='Asia/Shanghai'

# Configure LAN
# More options: https://openwrt.org/docs/guide-user/base-system/basic-networking
uci set network.lan.ipaddr="192.168.2.1"
uci commit network

# Configure WLAN2.4G
# More options: https://openwrt.org/docs/guide-user/network/wifi/basic#wi-fi_interfaces
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].ssid="CMMC-Z3et"
uci set wireless.@wifi-iface[0].key="kux6cdb3"
uci set wireless.@wifi-iface[0].ieee80211r='1'
uci commit wireless

# Configure WLAN5G
# More options: https://openwrt.org/docs/guide-user/network/wifi/basic#wi-fi_interfaces
uci set wireless.@wifi-device[1].disabled='0'
uci set wireless.@wifi-iface[1].disabled='0'
uci set wireless.@wifi-iface[1].encryption='sae'
uci set wireless.@wifi-iface[1].ssid="H3C-5G"
uci set wireless.@wifi-iface[1].key="123456789"
uci set wireless.@wifi-iface[1].ieee80211r='1'
uci commit wireless

# Configure PPPoE
# More options: https://openwrt.org/docs/guide-user/network/wan/wan_interface_protocols#protocol_pppoe_ppp_over_ethernet
uci set network.wan.proto='pppoe'
uci set network.wan.username="15865172459"
uci set network.wan.password="905539"
uci set network.wan.ipv6='auto'
uci del network.wan6
uci commit network

# Configure 
# More options: https://openwrt.org/docs/guide-user/network/network_configuration?s[]=globals&s[]=packet&s[]=steering#section_globals

echo "All done!"